#!/usr/bin/env bash
# ============================================================
# DLL e-commerce -- one-click deploy script
# Usage:
#   ./deploy.sh              deploy code and start services
#   ./deploy.sh --sync-db    deploy + sync database
#   ./deploy.sh --db-only    sync database only
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env.production"

# ---------- colors ----------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()   { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!!]${NC} $1"; }
error() { echo -e "${RED}[ERR]${NC} $1"; exit 1; }
info()  { echo -e "${CYAN}[->]${NC} $1"; }

# ---------- parse args ----------
SYNC_DB=false
DB_ONLY=false

for arg in "$@"; do
  case ${arg} in
    --sync-db)  SYNC_DB=true ;;
    --db-only)  DB_ONLY=true; SYNC_DB=true ;;
    --help|-h)
      echo "Usage: ./deploy.sh [options]"
      echo "  --sync-db    deploy then sync local db to server"
      echo "  --db-only    sync database only (no redeploy)"
      echo "  --help       show this help"
      exit 0
      ;;
    *) error "unknown argument: ${arg}" ;;
  esac
done

# ---------- check .env.production ----------
if [[ ! -f "${ENV_FILE}" ]]; then
  error "not found: ${ENV_FILE}"
fi

# load env (skip comments and blank lines)
load_env() {
  local file="$1"
  while IFS='=' read -r key value; do
    [[ -z "${key}" || "${key}" =~ ^[[:space:]]*# ]] && continue
    key=$(echo "${key}" | xargs)
    export "${key}"="${value}"
  done < "${file}"
}
load_env "${ENV_FILE}"

# ---------- validate required ----------
if [[ "${SERVER_HOST:-}" == "your_server_ip" || -z "${SERVER_HOST:-}" ]]; then
  error "please set SERVER_HOST in .env.production"
fi

SERVER_USER="${SERVER_USER:-root}"
SERVER_PORT="${SERVER_PORT:-22}"
DEPLOY_PATH="${DEPLOY_PATH:-/opt/dll-store}"

# ---------- auto-generate secrets ----------
generate_secret() {
  openssl rand -hex 32
}

UPDATED=false

if [[ -z "${JWT_SECRET:-}" ]]; then
  JWT_SECRET=$(generate_secret)
  sed -i.bak "s/^JWT_SECRET=$/JWT_SECRET=${JWT_SECRET}/" "${ENV_FILE}"
  UPDATED=true
  log "auto-generated JWT_SECRET"
fi

if [[ -z "${COOKIE_SECRET:-}" ]]; then
  COOKIE_SECRET=$(generate_secret)
  sed -i.bak "s/^COOKIE_SECRET=$/COOKIE_SECRET=${COOKIE_SECRET}/" "${ENV_FILE}"
  UPDATED=true
  log "auto-generated COOKIE_SECRET"
fi

if [[ -z "${POSTGRES_PASSWORD:-}" ]]; then
  POSTGRES_PASSWORD=$(generate_secret)
  sed -i.bak "s/^POSTGRES_PASSWORD=$/POSTGRES_PASSWORD=${POSTGRES_PASSWORD}/" "${ENV_FILE}"
  UPDATED=true
  log "auto-generated POSTGRES_PASSWORD"
fi

rm -f "${ENV_FILE}.bak"

if [[ "${UPDATED}" == true ]]; then
  warn "secrets written to .env.production -- keep it safe"
  load_env "${ENV_FILE}"
fi

# ---------- SSH config ----------
SSH_CMD="ssh -p ${SERVER_PORT} -o ConnectTimeout=10 -o StrictHostKeyChecking=accept-new"
SSH_TARGET="${SERVER_USER}@${SERVER_HOST}"
SCP_CMD="scp -P ${SERVER_PORT} -o ConnectTimeout=10"

# ---------- check SSH ----------
info "checking SSH connectivity..."
if ! ${SSH_CMD} "${SSH_TARGET}" "echo ok" &>/dev/null; then
  error "cannot connect to ${SSH_TARGET}:${SERVER_PORT} -- check SSH config"
fi
log "SSH connected: ${SSH_TARGET}"

# ---------- check Docker ----------
info "checking Docker on server..."
if ! ${SSH_CMD} "${SSH_TARGET}" "command -v docker &>/dev/null && docker compose version &>/dev/null"; then
  error "Docker/Docker Compose not found on server. Install: curl -fsSL https://get.docker.com | sh"
fi
log "Docker ready"

# ---------- db-only mode ----------
if [[ "${DB_ONLY}" == true ]]; then
  info "db-only mode..."
  bash "${SCRIPT_DIR}/scripts/db-sync.sh"
  log "database sync done"
  exit 0
fi

# ---------- sync code to server ----------
info "syncing project files to ${DEPLOY_PATH} ..."

${SSH_CMD} "${SSH_TARGET}" "mkdir -p ${DEPLOY_PATH}"

info "packing project files..."
ARCHIVE="/tmp/dll-deploy-$(date +%s).tar.gz"

tar \
  --exclude='node_modules' \
  --exclude='.next' \
  --exclude='.medusa' \
  --exclude='.env' \
  --exclude='.env.local' \
  --exclude='.env.production' \
  --exclude='.git' \
  --exclude='backups' \
  --exclude='medusa-nextjs-ecommerce.bak' \
  --exclude='.DS_Store' \
  --exclude='*.log' \
  -czf "${ARCHIVE}" \
  -C "${SCRIPT_DIR}" \
  .

ARCHIVE_SIZE=$(du -sh "${ARCHIVE}" | cut -f1)
info "archive size: ${ARCHIVE_SIZE}, uploading..."

${SCP_CMD} "${ARCHIVE}" "${SSH_TARGET}:/tmp/dll-deploy.tar.gz"
${SSH_CMD} "${SSH_TARGET}" "cd ${DEPLOY_PATH} && tar xzf /tmp/dll-deploy.tar.gz && rm -f /tmp/dll-deploy.tar.gz"

rm -f "${ARCHIVE}"

log "code synced"

# ---------- generate server .env ----------
info "generating server .env..."

STORE_CORS="http://${SERVER_HOST}:8000"
ADMIN_CORS="http://${SERVER_HOST}:9000"
AUTH_CORS="http://${SERVER_HOST}:9000,http://${SERVER_HOST}:8000"

cat > /tmp/dll-prod.env << EOF
# DLL production env -- generated by deploy.sh
JWT_SECRET=${JWT_SECRET}
COOKIE_SECRET=${COOKIE_SECRET}

POSTGRES_USER=${POSTGRES_USER:-medusa}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB:-medusa_db}

STORE_CORS=${STORE_CORS}
ADMIN_CORS=${ADMIN_CORS}
AUTH_CORS=${AUTH_CORS}

STRIPE_API_KEY=${STRIPE_API_KEY:-}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
NEXT_PUBLIC_STRIPE_KEY=${NEXT_PUBLIC_STRIPE_KEY:-}

NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY:-}
NEXT_PUBLIC_BASE_URL=http://${SERVER_HOST}:8000
NEXT_PUBLIC_DEFAULT_REGION=${NEXT_PUBLIC_DEFAULT_REGION:-us}
EOF

${SCP_CMD} /tmp/dll-prod.env "${SSH_TARGET}:${DEPLOY_PATH}/.env"
rm -f /tmp/dll-prod.env

log "env uploaded"

# ---------- build & start ----------
info "building and starting services on server (this may take a few minutes)..."

${SSH_CMD} "${SSH_TARGET}" "cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml up -d --build" 2>&1 | tail -20

log "docker compose started"

# ---------- health check ----------
info "waiting for services..."

MAX_WAIT=120
WAITED=0

while [[ ${WAITED} -lt ${MAX_WAIT} ]]; do
  STATUS=$(${SSH_CMD} "${SSH_TARGET}" "cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml ps --format '{{.Service}} {{.State}}' 2>/dev/null" || echo "")

  MEDUSA_UP=$(echo "${STATUS}" | grep -c "medusa.*running" || true)
  STORE_UP=$(echo "${STATUS}" | grep -c "storefront.*running" || true)

  if [[ "${MEDUSA_UP}" -ge 1 && "${STORE_UP}" -ge 1 ]]; then
    break
  fi

  sleep 5
  WAITED=$((WAITED + 5))
  echo -n "."
done
echo ""

if [[ ${WAITED} -ge ${MAX_WAIT} ]]; then
  warn "startup timeout -- check manually:"
  warn "  ${SSH_CMD} ${SSH_TARGET} 'cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml logs --tail 50'"
else
  log "all services running"
fi

# ---------- sync db (optional) ----------
if [[ "${SYNC_DB}" == true ]]; then
  info "syncing database..."
  bash "${SCRIPT_DIR}/scripts/db-sync.sh"
  log "database sync done"
fi

# ---------- summary ----------
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  DLL Deploy Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "  Storefront:  ${CYAN}http://${SERVER_HOST}:8000${NC}"
echo -e "  Admin Panel: ${CYAN}http://${SERVER_HOST}:9000/app${NC}"
echo ""
echo -e "  Server path: ${DEPLOY_PATH}"
echo ""
echo -e "  Commands (on server):"
echo -e "    logs:    cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml logs -f"
echo -e "    restart: cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml restart"
echo -e "    stop:    cd ${DEPLOY_PATH} && docker compose -f docker-compose.prod.yml down"
echo ""
